
apiVersion: v1 
kind: Pod
metadata: 
  name: podwithvolume
  labels:
    env: dev
spec: 
  containers:
    - name: nginx
      image: nginx 
      ports: 
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-volume
          readOnly: true
  volumes:
    - name: nginx-volume
      hostPath:
        path: /Users/adi-dev-mac/dev-env/lab/cka/pods/html
        type: Directory 