apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: respondent-marketing-site
  ports:
    - protocol: TCP
      port: 80        # The port inside the cluster
      targetPort: 80  # The container port
      nodePort: 30080 # The external port (must be between 30000-32767)